# Companies
store:
    path: store
    controller: App\Controller\CompanyController::store
    methods: [POST]


# Campaigns
campaign_create:
    path: campaign/create
    controller: App\Controller\CompanyCampaignController::createCampaign
    methods: [POST]

campaign_update:
    path: campaign/update/{id}
    controller: App\Controller\CompanyCampaignController::updateCampaign
    methods: [PUT]

campaign_delete:
    path: campaign/delete/{id}
    controller: App\Controller\CompanyCampaignController::deleteCampaign
    methods: [DELETE]

campaign_by_id:
    path: campaign/{id}
    controller: App\Controller\CompanyCampaignController::campaignById
    methods: [GET]

campaigns:
    path: campaigns
    controller: App\Controller\CompanyCampaignController::allCampaigns
    methods: [GET]


# Traffic Transactions

traffic_transaction_create:
    path: traffic_transaction/create
    controller: App\Controller\CompanyTrafficTransactionController::createTrafficTransaction
    methods: [POST]

traffic_transaction_update:
    path: traffic_transaction/update/{id}
    controller: App\Controller\CompanyTrafficTransactionController::updateTrafficTransaction
    methods: [PUT]

traffic_transaction_delete:
    path: traffic_transaction/delete/{id}
    controller: App\Controller\CompanyTrafficTransactionController::deleteTrafficTransaction
    methods: [DELETE]

traffic_transactions:
    path: traffic_transactions
    controller: App\Controller\CompanyTrafficTransactionController::allTrafficTransactions
    methods: [GET]

