store:
    path: store
    controller: App\Controller\CompanyController::store
    methods: [POST]

create_campaign:
    path: create/campaign
    controller: App\Controller\CompanyCampaignController::createCampaign
    methods: [POST]

update_campaign:
    path: update/campaign/{id}
    controller: App\Controller\CompanyCampaignController::updateCampaign
    methods: [PUT]

delete_campaign:
    path: delete/campaign/{id}
    controller: App\Controller\CompanyCampaignController::deleteCampaign
    methods: [DELETE]
